# Generated by Django 5.1.5 on 2025-01-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='file_path',
            field=models.FilePathField(max_length=255),
        ),
    ]
