# Generated by Django 5.1.5 on 2025-01-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics_handler', '0002_alter_docs_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='file_path',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='userstodocs',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
