# Generated by Django 5.1.5 on 2025-01-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics_handler', '0003_alter_docs_file_path_alter_userstodocs_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='file_original_name',
            field=models.CharField(default='image.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='docs',
            name='file_path',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='userstodocs',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
