# Generated by Django 5.1.5 on 2025-02-06 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics_handler', '0004_docs_file_original_name_alter_docs_file_path_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='docs',
            table='docs',
        ),
        migrations.AlterModelTable(
            name='userstodocs',
            table='users_to_docs',
        ),
    ]
