# Generated by Django 5.1.5 on 2025-01-27 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pics_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_type', models.CharField(choices=[('jpg', 'JPEG Image'), ('pdf', 'PDF Document'), ('png', 'PNG Image')], unique=True)),
                ('price', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_price', models.FloatField()),
                ('payment', models.BooleanField()),
                ('docs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pics_handler.docs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pics_handler.userstodocs')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
