# Generated by Django 5.1.5 on 2025-02-06 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_cart_user_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
        migrations.AlterModelTable(
            name='price',
            table='price',
        ),
    ]
